version: "3.9"

services:
  mongo:
    image: mongo
    container_name: antimosquito-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    container_name: antimosquito-dbdata
    restart: unless-stopped
    volumes:
      - /data/db
  web:
    container_name: antimosquito-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/web.dockerfile
    ports:
      - "80:5000"
    depends_on:
      mongo:
        condition: service_started
