name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 創建/更新 分支
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: "code/rearEnd"
          TARGET_BRANCH: "rearEnd"
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.email "a102009102009@gmail.com"
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin $TARGET_BRANCH # push to remote branch
